# Automatically build multi-architectural tagged container images and push them to DockerHub.
# https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Automatic-Builds
#
# - targeted platforms: x86_64, PowerPC64, ARM64
# - master is built as fnndsc/{{ cookiecutter.app_repo_name }}:latest
# - git tags are built as fnndsc/{{ cookiecutter.app_repo_name }}:<tag>

name: publish

on:
  push:
    branches: [ master ]
    tags: ['**']

{% raw %}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get git tag
        id: git_info
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
      - name: Determine image tag name
        id: determine
        env:
          git_tag: ${{ steps.git_info.outputs.tag }}
        run: |
          dock_image="${GITHUB_REPOSITORY,,}"  # to lower case
          # if build triggered by tag, use tag name
          tag="${git_tag:-latest}"
          echo "::set-output name=tag::$dock_image:$tag"
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64,ppc64le
      - uses: docker/setup-buildx-action@v1
        id: buildx
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ steps.buildx.outputs.platforms }}
          tags: ${{ steps.determine.outputs.tag }}
          # push: true
{% endraw %}
