# run everything just to make sure it works!

name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install python dependencies
        run: pip install cookiecutter pyyaml
      - name: Validate YAML
        run: python -m unittest tests/test_ghactionsyaml.py

  test:
    name: E2E integration test
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: cookiecutter-chrisapp
      - name: setup CUBE
        uses: fnndsc/minimake@v2
      - name: install cookiecutter
        run: |
          pip install cookiecutter
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: test
        run: ./cookiecutter-chrisapp/tests/example.sh cookiecutter-chrisapp
